CC = g++
CFLAGS = -g -Wall -I


veri: main.cpp filterStructureImplementer.c verilogWriter.c main.h structures.h 
	$(CC) -o ./BUILD/veri.exe ./SRC/main.cpp ./SRC/filterStructureImplementer.c ./SRC/verilogWriter.c

