CC = g++
CFLAGS = -g -Wall -I


veri: ./SRC/main.cpp ./SRC/filterStructureImplementer.c ./SRC/verilogWriter.c ./SRC/main.h ./SRC/structures.h 
	$(CC) -o ./BUILD/veri.exe ./SRC/main.cpp ./SRC/filterStructureImplementer.c ./SRC/verilogWriter.c 

